Repository ucsb-cs156-s23/proj-gauchoride-s23-5pm-4, pull requests merged in 2023-06, with the labels that each got.

#25 Michael improve user controller api param documentation
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/UsersController.java
Labels: 5, Merge Candidate (CI/CD)

#33 Sophia - adding ROLE_DRIVER to backend
  src/main/java/edu/ucsb/cs156/gauchoride/config/SecurityConfig.java
Labels: INSTRUCTOR: assign points

#27 amey - Add entity and repository file for Driver shift table
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Shift.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/ShiftRepository.java
Labels: FIXME: Peer code review

#44 Pc update workflows
  .github/workflows/10-backend-unit.yml
  .github/workflows/12-backend-jacoco.yml
  .github/workflows/13-backend-incremental-pitest.yml
  .github/workflows/14-backend-pitest.yml
  .github/workflows/30-frontend-tests.yml
  .github/workflows/32-frontend-coverage.yml
  .github/workflows/33-frontend-pr-mutation-testing.yml
  .github/workflows/34-frontend-main-mutation-testing.yml
  .github/workflows/36-frontend-eslint.yml
  .github/workflows/52-storybook-main-branch.yml
  .github/workflows/54-storybook-pr.yml
  .github/workflows/56-javadoc-main-branch.yml
  .github/workflows/58-javadoc-pr.yml
Labels: staff

#32 Sophia - adding Ride Request Table
  frontend/src/fixtures/rideFixtures.js
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/components/Ride/RideTable.js
  frontend/src/main/utils/rideUtils.js
  frontend/src/stories/components/Ride/RideForm.stories.js
  frontend/src/stories/components/Ride/RideTable.stories.js
  frontend/src/tests/components/Ride/RideForm.test.js
  frontend/src/tests/components/Ride/RideTable.test.js
  frontend/src/tests/utils/rideUtils.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/ShiftRepository.java
Labels: 10, Merge Candidate (CI/CD)

#48 pc - fix mutation testing for ProfilePage
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/main/pages/ProfilePage.js
  frontend/src/tests/pages/ProfilePage.test.js
Labels: staff

#36 Sophia - add Rider Create Page
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/pages/Ride/RideRequestCreatePage.js
  frontend/src/stories/pages/Ride/RideRequestCreatePage.stories.js
  frontend/src/tests/pages/Ride/RideRequestCreatePage.test.js
Labels: 10

#38 Sophia - adding Rider Edit Page
  frontend/src/main/components/Ride/RideForm.js
  frontend/src/main/pages/Ride/RideRequestEditPage.js
  frontend/src/stories/pages/Ride/RideRequestEditPage.stories.js
  frontend/src/tests/pages/Ride/RideRequestEditPage.test.js
Labels: FIXME: Peer code review

#55 Anikait - Edit Operation for Rides, with combined path for all roles
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RideControllerTests.java
Labels: 10

#56 Ameymwalimbe shift get post
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/ShiftController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Shift.java
  src/main/java/edu/ucsb/cs156/gauchoride/repositories/ShiftRepository.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/ShiftControllerTests.java
Labels: FIXME: Peer code review

#51 Ian - Driver shift page navbar button
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/fixtures/shiftFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Shift/ShiftTable.js
  frontend/src/main/pages/ShiftPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Shift/ShiftTable.test.js
  frontend/src/tests/pages/ShiftPage.test.js
Labels: FIXME: Peer code review

#60 Anikait/Sophia - Add Student Name to Ride Entity, fix ride table bug, add ride to navbar
  frontend/src/App.js
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/fixtures/rideFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Ride/RideTable.js
  frontend/src/main/pages/Ride/RideRequestIndexPage.js
  frontend/src/stories/components/Ride/RideForm.stories.js
  frontend/src/stories/components/Ride/RideTable.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Ride/RideTable.test.js
  src/main/java/edu/ucsb/cs156/gauchoride/controllers/RideController.java
  src/main/java/edu/ucsb/cs156/gauchoride/entities/Ride.java
  src/test/java/edu/ucsb/cs156/gauchoride/controllers/RideControllerTests.java
Labels: FIXME: Peer code review
